# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Bioinformatics
author: Wageningen University & Reseach - Ridder, Dick de; Kupczok, Anne; Holmer, Rens; Bakker, Freek; Hooft, Justin van der; Risse, Judith; Navarro, Jorge; Sardjoe, Tomer.
logo: BIF logo.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: BIF20306reader.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
    - references.bib
# Information about where the book exists on the web
# repository:
#  url: https://git.wur.nl/bioinformatics/bif20806-reader  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#use_issues_button: true
#use_repository_button: true

#######################################################################################
# HTML settings
html:
  extra_footer: |
    <p>
    Text in the reader is provided under a <a href="https://creativecommons.org/">Creative Commons</a> <a href="https://creativecommons.org/licenses/by-nc/4.0/">BY-NC 4.0</a> license.
    Figures have their licenses stated individually.
    </p>

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

#######################################################################################
# Advanced and power-user settings
sphinx:
  config: 
    html_show_copyright: false
    bibtex_default_style: unsrt
    bibtex_reference_style: author_year
    language: en
  extra_extensions: 
    - sphinx_subfigure
